name: Add a new GitHub Project card to the specified project column based on issue labels
on: ['issues']
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-sre-tech-radar-project
      uses: docker://takanabe/github-actions-automate-projects:latest
      if: github.event_name == 'issues' && github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'Category:Tech Radar')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/Gamemap/Godot/projects/3
        GITHUB_PROJECT_COLUMN_NAME: Backlog
    - name: mark_closed
      uses: docker://takanabe/github-actions-automate-projects:latest
      if: github.event_name == 'issues' && github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'Type:Closed')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/Gamemap/Godot/projects/3
        GITHUB_PROJECT_COLUMN_NAME: Closed
    - name: add-new
      uses: docker://takanabe/github-actions-automate-projects:latest
      if: github.event_name == 'issues' && github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'Type:bug')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/Gamemap/Godot/projects/3
        GITHUB_PROJECT_COLUMN_NAME: High priority
