name: Add a new GitHub Project card linked to a GitHub issue to the specified project column
on: [issues, pull_request]
jobs:
  github-actions-automate-projects:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event.label.name == 'To Do'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/Gamemap/Godot/projects/3
        GITHUB_PROJECT_COLUMN_NAME: To Do
    - name: add-new-prs-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event.label.name =='Closed'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/Gamemap/Godot/projects/3
        GITHUB_PROJECT_COLUMN_NAME: Closed
